version: '3.8'

services:
  keydb:
    image: eqalpha/keydb
    container_name: keydb
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - keydb-data:/data
    environment:
      - TZ=UTC
      - KEYDB_DATABASES=${KEYDB_DATABASES}
      - KEYDB_PASS=${KEYDB_PASSWORD} # Uncomment and set a password if needed

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

volumes:
  keydb-data:
    driver: local
